### PR TITLE
Added safari10 mangle option in terser

### PR DESCRIPTION
**Pull request by trimethia**
On older iOS devices, the current card can't be displayed and outputs the following error:
`button-card.js:69.0 SyntaxError: Cannot declare a const variable twice: 't'`

After a quick search I believe this is due to an [ES6 bug in Safari 10](https://bugs.webkit.org/show_bug.cgi?id=171041).

Terser provides a [mangle option to fix this issue](https://github.com/terser/terser#mangle-options). I verified that the card generated after adding this option to terser and running using `npm run build` is displayed correctly on my iOS device.

### CODE REVIEW

**Comment by iantrich** [comment]
I'll try to do some testing on different devices types with this over the weekend.

@trimethia did you just check on your iOS device?

**Comment by trimethia** [comment]
> @trimethia did you just check on your iOS device?

Yes, it displays fine in my device.

**Comment by iantrich** [comment]
I mean, did you try any other device types?

**Comment by trimethia** [comment]
Also tried safari on a mac and seemed fine.

**Comment by RomRider** [comment]
Will be included in next release, I'm closing this one as I've changed how the module is built. Thanks @trimethia!

**Pull request closed without merging**
