### PR TITLE
Localization fix

### PR DESCRIPTION
**Pull request by ildar170975**
May be I missed something, did not go to deep...

After fix:
изображение

### CODE REVIEW

**Comment by gerard33** [comment]
@ildar170975 can you share the `button-card.js` file so I can do some additional testing? Tried to build it myself but failed until now...

**Comment by ildar170975** [comment]
https://community.home-assistant.io/t/lovelace-button-card/65981/6883?u=ildar_gabdullin

**Comment by ildar170975** [comment]
Answering from iPhone, cannot edit my previous post in a magnificent Safari browser((((. In short - I was unable to create JS-file myself, had to edit the obfuscated JS-file....

**Comment by clearwave1** [comment]
This looks like it is ready to be released.

Forgive my ignorance, but what is the next step to getting it released and why is it taking so long?

**Comment by ildar170975** [comment]
To be honest, my fix does not include backward compatibility for earlier HA versions.

**Comment by RomRider** [comment]
I'm closing this as I pushed a new beta version with backward compatibility.
Thanks for your patience and for the patch :)

**Comment by ildar170975** [comment]
@RomRider 
thank you very very much!!!!

**Pull request closed without merging**
