### PR TITLE
_template deprecation and custom fields support

### LINKED ISSUE #187: add external entity in action:, preferably with templatable entities
**Is your feature request related to a problem? Please describe.**
trying to have an other entity serviced in the tap-action than the button entity, I can only do that hard coded right now:
```
    - type: custom:button-card
        template: button_motion
        name: Corridor <br> office
        entity: binary_sensor.corridor_office_motion_sensor
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.corridor_office_motion_sensor_switch
```

please create a template in the action field to be able to do this:
```
      - type: custom:button-card
        template: button_motion
        name: Corridor
        entity: binary_sensor.name
        tap_action:
          action: call-service
          service: switch.toggle
          service_data_template:
            entity_id: >
              'switch.' + entity.object_id + '_switch'
```

maybe make it even shorter like:

```
        tap-action:
          action: toggle
          entity_id: switch.corridor_office_motion_sensor_switch
```
and with template:
```
        tap-action:
          action: toggle
          data_template:
            entity_id: >
              'switch.' + entity.object_id + '_switch'
```

**
**Additional context**
Please see https://community.home-assistant.io/t/lovelace-button-card/65981/1715?u=mariusthvdb

thanks for considering !

### LINKED ISSUE #200: more-info dialog always opens on tap if button-card is placed inside entities card
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
If the button card is placed inside and entities card, no matter what tap_action I provide, the more-info dialog opens (and the action is also performed)

**Version of the card**
Version: 1.11.1

**To Reproduce**
This is the configuration I used:
```yaml

  - type: entities
    entities:
    - type: "custom:button-card"
      entity: switch.sw1
      name: Button in entities
      tap_action: 
        action: toggle
      
  - type: "custom:button-card"
    entity: switch.sw1
    name: Button
    tap_action: 
      action: toggle
```

**Expected behavior**
I would expect the more-dialog to not show unless it is the action provided in tap_action

**Desktop (please complete the following information):**
 - Browser chrome Win, Linux
 - Version 75

**Smartphone (please complete the following information):**
 - Device: oneplus6
 - OS: Android 9
 - Browser Chrome
 - Version ?

**Additional context**
Only seems to appear when the button card is inside entities, however, it is the only way I have found to be able to stack vertically 2 buttons and be able to style the background nicely using card-mod

### PR DESCRIPTION
**Pull request by RomRider**
**BREAKING CHANGES**
* All the `*_template` are now deprecated 😨 but they are replaced with a better way of handling templates. 🎉 
  This applies to:
  * `name`
  * `label`
  * `entity_picture`
  * `value` in the state object when `operator: template`
  
  Old style:
  ```yaml
  name_template: >
    if (entity.state === 'off') return 'Template is off';
    return 'Template is on';
  ```
  Becomes for example:
  ```yaml
  name: >
    [[[
      if (entity.state === 'off') return 'Template is off';
      return 'Template is on';
    ]]]
  ```
  Without templating, no change:
  ```yaml
  name: This is not a template
  ```

**NEW FEATURES**
* All the states values support templating, it's optional of course:
  ```yaml
  entity: sensor.first_sensor
  state:
    - operator: '<'
      value: '[[[ states["sensor.other_sensor"].state ]]]`
  ```
* `icon` supports templating (use the new templating format `[[[ template ]]]`)
  ```yaml
  - type: custom:button-card
    icon: >
      [[[
        if (entity.state === 'on')
          return "mdi:fire";
        return "mdi:lightbulb";
      ]]]
    entity: switch.skylight
  ```
* Every `styles` entry now also supports templating, or plan text of course:
  ```yaml
  styles:
    card:
      - background-color: >
          [[[ if (states['input_number.test'].state == 0) return "green"; return "red"; ]]]
  ```
* Every field in `*_action` support templating, or plain text of course, including `service_data` (fixes #187):
  ```yaml
  tap_action:
    action: call-service
    service: >
      [[[
        if (states['input_number.test'].state <= 20)
          return "input_number.increment";
        return "input_number.decrement";
      ]]]
    service_data:
      entity_id: input_number.test
  ```
* Custom fields support for your button through the new `custom_fields` object. This will enable you to define your own fields in the button and apply styles to them without writing hundreds of line of javascript. This is an advanced feature, you'll have to understand how CSS (and CSS grids) work! You'll have more control on how to position those fields in the button compared to previously where you only had more or less 2 fields to play with (`name` and `label`).
  Your custom field content can be plain text or a template `[[[ ]]]`
  Your custom element can be styled also using `styles.custom_fields.<ELEMENT_NAME>`. See below for examples:
  * Placing an element wherever you want (that means bypassing the grid). Set the grid to `position: relative` and set the element to `position: absolute`
    Jul-21-2019 16-34-46
    ```yaml
      - type: custom:button-card
        icon: mdi:lightbulb
        aspect_ratio: 1/1
        name: Nb lights on
        styles:
          grid:
            - position: relative
          custom_fields:
            notification:
              - background-color: >
                  [[[
                    if (states['input_number.test'].state == 0)
                      return "green";
                    return "red";
                  ]]]
              - border-radius: 50%
              - position: absolute
              - left: 60%
              - top: 10%
              - height: 20px
              - width: 20px
              - font-size: 8px
              - line-height: 20px
        custom_fields:
          notification: >
            [[[ return Math.floor(states['input_number.test'].state / 10) ]]]
    ```
  * Or you can use the grid. Each element will have it's name positioned as the `grid-area` (Thanks @iantrich @lbdab and @jimz011 for the inspiration):
    imageimage

    ```yaml
      - type: custom:button-card
        entity: 'sensor.raspi_temp'
        icon: 'mdi:raspberry-pi'
        aspect_ratio: 1/1
        name: HassOS
        styles:
          card:
            - background-color: '#000044'
            - border-radius: 10%
            - padding: 10%
            - color: ivory
            - font-size: 10px
            - text-shadow: 0px 0px 5px black
            - text-transform: capitalize
          grid:
            - grid-template-areas: '"i temp" "n n" "cpu cpu" "ram ram" "sd sd"'
            - grid-template-columns: 1fr 1fr
            - grid-template-rows: 1fr min-content min-content min-content min-content
          name:
            - font-weight: bold
            - font-size: 13px
            - color: white
            - align-self: middle
            - justify-self: start
            - padding-bottom: 4px
          img_cell:
            - justify-content: start
            - align-items: start
            - margin: none
          icon:
            - color: >
                [[[
                  if (entity.state < 60) return 'lime';
                  if (entity.state >= 60 && entity.state < 80) return 'orange';
                  else return 'red';
                ]]]
            - width: 70%
            - margin-top: -10%
          custom_fields:
            temp:
              - align-self: start
              - justify-self: end
            cpu:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - --text-color-sensor: '[[[ if (states["sensor.raspi_cpu"].state > 80) return "red"; ]]]'
            ram:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - --text-color-sensor: '[[[ if (states["sensor.raspi_ram"].state > 80) return "red"; ]]]'
            sd:
              - align-self: middle
              - justify-self: start
              - --text-color-sensor: '[[[ if (states["sensor.raspi_sd"].state > 80) return "red"; ]]]'
        custom_fields:
          temp: >
            [[[
              return `<ha-icon
                icon="mdi:thermometer"
                style="width: 12px; height: 12px; color: yellow;">
                </ha-icon><span>${entity.state}°C</span>`
            ]]]
          cpu: >
            [[[
              return `<ha-icon
                icon="mdi:server"
                style="width: 12px; height: 12px; color: deepskyblue;">
                </ha-icon><span>CPU: <span style="color: var(--text-color-sensor);">${states['sensor.raspi_cpu'].state}%</span></span>`
            ]]]
          ram: >
            [[[
              return `<ha-icon
                icon="mdi:memory"
                style="width: 12px; height: 12px; color: deepskyblue;">
                </ha-icon><span>RAM: <span style="color: var(--text-color-sensor);">${states['sensor.raspi_ram'].state}%</span></span>`
            ]]]
          sd: >
            [[[
              return `<ha-icon
                icon="mdi:harddisk"
                style="width: 12px; height: 12px; color: deepskyblue;">
                </ha-icon><span>SD: <span style="color: var(--text-color-sensor);">${states['sensor.raspi_sd'].state}%</span></span>`
            ]]]
    ```
**BUGFIXES**
* Fixes #200: Using `button-card` inside an `entities` card will not fire more-info anymore automatically.

### CODE REVIEW

**Comment by iantrich** [comment]
html still works though, right? Excited to see the possibilities

**Comment by RomRider** [comment]
Yeah, everything works the same as before :)
But you can do things like that now:
Jul-21-2019 16-34-46
```yaml
      - type: custom:button-card
        icon: mdi:lightbulb
        aspect_ratio: 1/1
        name: Nb lights on
        styles:
          grid:
            - position: relative
          custom_fields:
            notification:
              - background-color: >
                  [[[ if (states['input_number.test'].state == 0) return "green"; return "red" ]]]
              - border-radius: 50%
              - position: absolute
              - left: 60%
              - top: 10%
              - height: 20px
              - width: 20px
              - font-size: 8px
              - line-height: 20px
        custom_fields:
          notification: >
            [[[ return Math.floor(states['input_number.test'].state / 10) ]]]
```

**Comment by Mariusthvdb** [comment]
HI, this is a major development! great.

Just to be sure: in the examples above the `;` is not used in all templates. Maybe those are typo's, or did you change the templating logic?

this 

name: >
```
  [[[
    if (entity.state === 'off') return 'Template is off'
    return 'Template is on'
  ]]]
```

would have to be

```
name: >
  [[[
    if (entity.state === 'off') return 'Template is off';
    return 'Template is on';
  ]]]
```

and 

```
   - background-color: >
                  [[[ if (states['input_number.test'].state == 0) return "green"; return "red" ]]]
```

should really be:

```
   - background-color: >
                  [[[ if (states['input_number.test'].state == 0) return "green"; return "red";]]]

```
and:

```
  service: >
    [[[
      if (states['input_number.test'].state <= 20)
        return "input_number.increment"
      return "input_number.decrement"
    ]]]
```

should be:

```
  service: >
    [[[
      if (states['input_number.test'].state <= 20)
        return "input_number.increment";
      return "input_number.decrement";
    ]]]
```

?

or is the need for the `; `deprecated also ;-)

**Comment by RomRider** [comment]
It is javascript, `;` is not always mandatory, but you should keep it. I'll update the examples so that it shows up. :)

**Comment by Mariusthvdb** [comment]
> It is javascript, `;` is not always mandatory, but you should keep it. I'll update the examples so that it shows up. :)

great, thanks. Wouldn't that ( the use of the ending  `;` 's) allow to leave out the [[[ and ]]] ? Using these hooks is so awkward, compared to the clean templates without them:

```
  service: >
      if (states['input_number.test'].state <= 20) return "input_number.increment";
      return "input_number.decrement";
```

reads so much easier, and I would expect it to be less error prone.

**Comment by RomRider** [comment]
> reads so much easier, and I would expect it to be less error prone.

That's lazyness, for 6 characters ;) And what if you want to print `;` at the end of your string without doing javascript?
The `[[[ ]]]` is very explicit.

**Comment by Mariusthvdb** [comment]
> > reads so much easier, and I would expect it to be less error prone.
> 
> That's lazyness, for 6 characters ;) And what if you want to print `;` at the end of your string without doing javascript?
> The `[[[ ]]]` is very explicit.

yes, appreciate that. It's just that with the various custom cards being developed in HA, each seems to adhere to their own 'version' of javascript...
It would be very nice if plain and default javascript could be used, without having to take care the custom-card specifics would have to be set.

no big deal breaker, but might be a topic the HA devs and CC devs could try to reach consensus on ;-)

**Comment by iantrich** [comment]
@Mariusthvdb that won't happen. #1 core lovelace will never support templates #2 there's no requirements for anyone making a custom card or really anyway to communicate that until after the fact at which point it is still up to the dev if they want to adhere or not. Providing utilities in custom-card-helpers is about the closest we could get.

**Comment by RomRider** [comment]
Still have to add documentation to this PR and a bunch of examples, I'm lazy lately when it comes to documentation...

**Comment by iantrich** [comment]
I hear that :)

**Comment by RomRider** [comment]
@iantrich, what do you think about the 2 examples regarding custom fields in the PR? Do you think it's more readable than before?
I kind of like this way of configuring a complex card as it's more descriptive and feels less cluttered.

**Comment by iantrich** [comment]
@RomRider I love it. The ability to have elements/templates contained in a separate grid allows for more efficient use of anchors in my case and I'm sure we'll find a lot more advantages as well.

**Comment by Mariusthvdb** [comment]
> @Mariusthvdb that won't happen. 1. core lovelace will never support templates 2. there's no requirements for anyone making a custom card or really anyway to communicate that until after the fact at which point it is still up to the dev if they want to adhere or not. Providing utilities in custom-card-helpers is about the closest we could get.

well, seems templating is starting to invade Lovelace. Finally: https://www.home-assistant.io/lovelace/markdown/#template-variables

and https://community.home-assistant.io/t/markdown-mod-improve-the-built-in-markdown-card/120745/53?u=mariusthvdb

Hope (expect) this will set a trend ;-)

**Comment by iantrich** [comment]
Doubt it but you never know I guess 🤷‍♀️

**Comment by daniel-stockhausen** [comment]
The values for `styles` key-value pairs don't seem to be interpreted:
```
- entity: binary_sensor.window_laundry_room
  type: custom:button-card
  styles:
    card:
    - background-color: >
        [[[ return 'red'; ]]]
    icon:
    - color: >
        [[[ return 'green'; ]]]
  icon: mdi:window-closed
```
no


```
- entity: binary_sensor.window_laundry_room
  type: custom:button-card
  styles:
    card:
    - background-color: >
        red
    icon:
    - color: >
        green
  icon: mdi:window-closed
```
yes

**Pull request merged**
