### PR TITLE
entity_picture/custom picture support with style

### LINKED ISSUE #3: Set own icon
Some mdi:icon are not working, like 
kitchen 
monitor-dashboard

both present in the mdi website .. or maybe I am wrong?

### LINKED ISSUE #125: Border clipping and can't use border-radius
See post here:
https://community.home-assistant.io/t/lovelace-button-card/65981/689

With V1.0.0 I’m seeing behavior similar to issue #114, square points behind rounded corners.
Here’s what I see using card_type: card, color, and with a border in the style: (using an entity whose state is ‘on’). (Both Firefox and Chrome)
```yaml
  - type: custom:button-card
    color_type: card
    color: rgb(245,116,56)
    style:
  #    - background-color: rgba(245,116,56,1)
      - border-radius: 30px
      - border: solid 3px rgba(118,185,0,1)
    entity: light.office_ceiling
    icon: mdi:stop
    name: BUTTON only CType card
    tap_action:
      action: call-service
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.firetv_living_room
        command: "input keyevent 86"
```
The color is applied out to the square corners, and the border is clipped on the right
image

Here’s what I see with no card_type or color, and background-color defined in style:
```yaml
  - type: custom:button-card
#    color_type: card
#    color: rgb(245,116,56)
    style:
      - background-color: rgba(245,116,56,1)
      - border-radius: 30px
      - border: solid 3px rgba(118,185,0,1)
    entity: light.office_ceiling
    icon: mdi:stop
    name: BUTTON only CType card
    tap_action:
      action: call-service
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.firetv_living_room
        command: "input keyevent 86"
```
The color does not get applied out to the square corners, but the corners are visible and the border is clipped on the right.
button2
image

### PR DESCRIPTION
**Pull request by RomRider**
**New Features**
* Entity Picture/Custom Picture support, per state and with styling (Fixes #3). New options are:
  * `show_entity_picture`, default is `false`
  * `entity_picture`
  * `entity_picture_style`

entity_picture

Example config looks like this:
```yaml
        - type: "custom:button-card"
          entity: switch.skylight
          entity_picture: https://upload.wikimedia.org/wikipedia/en/e/ed/Nyan_cat_250px_frame.PNG
          show_entity_picture: true
          name: Entity Picture Default
          state:
            - value: 'off'
              entity_picture_style:
                - filter: grayscale(100%)
                - border-radius: 50%
            - value: 'on'
              style:
                - animation: blink 2s ease infinite
              entity_picture_style:
                - border-radius: 50%
        - type: "custom:button-card"
          color_type: card
          entity: switch.skylight
          show_entity_picture: true
          name: Entity Picture State
          state:
            - value: 'off'
              color: black
              entity_picture: https://welovecatsandkittens.com/wp-content/uploads/2013/09/fallling-asleep-at-keyboard-cat.jpg
              entity_picture_style:
                - filter: grayscale(100%)
            - value: 'on'
              color: '#ce42f4'
              entity_picture: https://media.tenor.com/images/d740131a4906504d47cab865f1bd95b3/tenor.gif
```

**Fix**
* Fix #125 : Border Clipping & rounded corner

**Breaking Change**
* If using blink, the whole card will now blink. I might bring back only the icon/text blinking in the future.

**Others**
* Code cleanup

### CODE REVIEW

**Comment by arsaboo** [comment]
Love the idea...this will be great for switches/input_booleans. 

Is it possible for the `entity_picture` to occupy the entire button? I am guessing the answer is YES but just wanted to make sure.

**Comment by sparkydave1981** [comment]
Desperately hanging out for this to be merged so I can use pictures instead of icons.  Looks awesome!

**Comment by RomRider** [comment]
> Is it possible for the `entity_picture` to occupy the entire button? I am guessing the answer is YES but just wanted to make sure.

No @arsaboo, it replaces the icon. What use case do you have in mind? The [picture element](https://www.home-assistant.io/lovelace/picture-elements/) seems a better approach for this

**Comment by RomRider** [comment]
Ready for review @iantrich

**Pull request merged**
