### PR TITLE
Add rollup terser to decrease bundle size

### PR DESCRIPTION
**Pull request by iantrich**
Lowers distribution from 172KB to 60KB

### CODE REVIEW

**Comment by RomRider** [comment]
Good idea, thanks :)
Why is the `package.lock.json` so much modified? Some versions on your commit are older than the one used before. Is this expected?

**Comment by iantrich** [comment]
weird, I didn't really review the lock file, just ran npm install

**Comment by iantrich** [comment]
I think npm is trying to be smart about possible dependency conflicts.

**Comment by iantrich** [comment]
I think this is fine with the package json diff. What do you think?

**Comment by RomRider** [comment]
I'll integrate this to the next PR if you don't mind and close this one, what do you think? I just don't want to deal with merge conflicts 😅

**Pull request closed without merging**
