### PR TITLE
[WIP] Bring back paper-button and convert to TypeScript

### PR DESCRIPTION
**Pull request by iantrich**
Currently some issues with the resulting bundle
`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry at http://192.168.1.2:8123/local/button-card.js:1:41080`

### CODE REVIEW

**Comment by iantrich** [comment]
Need to determine how to exclude Polymer from the final bundle. @balloob provided this webpack example:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/config/webpack.js#L19-L24

**Comment by balloob** [comment]
Generally you want to avoid making web components that have no check around customElements.define a dependency. It means that if another card would include `paper-button`, you're now going to blow up loading your whole component, as an exception is raised within your bundle.

Better to make a standalone package for paper-button that people can install, that way it won't take down your bundle if it's already defined.

But really, the solution here is to not use `<paper-button>` at all? You're overriding so much styling, there is really no reason to use it at all. Just remove it?

**Comment by iantrich** [comment]
You suggest just using a good ole fashion button and let people add styles to their heart's content?

**Comment by balloob** [comment]
Yeah, just use: https://gist.github.com/MoOx/9137295

**Comment by iantrich** [comment]
Cool. This bundling has been a learning experience for me :) But this makes it a lot more straight-forward. Thanks!

**Comment by RomRider** [comment]
@iantrich, is this still a thing with the latest refactor?

**Comment by iantrich** [comment]
What do you mean?

**Comment by RomRider** [comment]
Can we close it?

**Pull request closed without merging**
