### PR TITLE
Various typos and fixes

### PR DESCRIPTION
**Pull request by 3ative**
I found a few 🤞

### CODE REVIEW

**Comment by RomRider** [comment]
Thanks!

**Comment by 3ative** [comment]
My pleasure.

**Comment by 3ative** [comment]
@RomRider 
Hey dude, 
Sorry to contact you via this thread but, I couldn't find anyway to PM / DM you. 
I wonder if you've seen my YouTube playlist on the 'Custom Button Card' : 
[](https://www.youtube.com/playlist?list=PLWRTMby105bghMzvCYV5Y2v1_dAeqILIG)

It's proving quite popular and is helping loads of users. So, any chance of them being added to the official docs?? 

Cheers.

**Comment by RomRider** [comment]
Sure! Great content, bravo! 👍👏 You should share it on the forum also!
Mind opening an issue so I don't forget? This being a PR and closed I can't track it.

Thanks :)

**Pull request merged**
