### PR TITLE
Add spin option to state object

### PR DESCRIPTION
**Pull request by iantrich**
Fixes https://github.com/custom-cards/button-card/issues/90

### CODE REVIEW

**Comment by RomRider** [comment]
@iantrich, should we also add a`spin` option for the main config?
Up until now most config options are duplicated in main config and state config which makes sense.

**Comment by iantrich** [comment]
So just an always spinning icon?

**Comment by RomRider** [comment]
Yes, that was my idea, to be able to something like:
For a label card
```yaml
- type: "custom:button-card"
  color_type: label-card
  name: Fans
  icon: mdi:fan
  spin: true
```

For an entity:
```yaml
- type: "custom:button-card"
  entity: switch.fan
  icon: mdi:link
  state:
    - value: 'on'
      spin: true
    - value: 'off'
      spin: false

**Comment by iantrich** [comment]
I don't think we should add it to the main. If someone wants it to always spin they can define all states.

**Comment by RomRider** [comment]
> If someone wants it to always spin they can define all states.
There's no state for the `label-card` for example as there's no entity defined

**Comment by iantrich** [comment]
Let's not try to cover every and all edge case and make this more complex than it already is.

**Pull request merged**
