### PR TITLE
[WIP] Move to custom-card-helpers, lint, terser

### PR DESCRIPTION
**Pull request by iantrich**
* Implemented custom-card-helpers (moved double tap, repeat and other differences to module)
* Added rollup terser to decrease bundle size
* Ran linter on all remaining files

### CODE REVIEW

**Comment by iantrich** [comment]
Setting this up to start work on timer functionality in https://github.com/custom-cards/button-card/issues/156

**Comment by iantrich** [comment]
eck, I broke something in actions. Will have to look into it later

**Comment by mclaudiopt** [comment]
is helper somekind of beta version?

**Comment by iantrich** [comment]
@mclaudiopt I don't follow your question

**Comment by iantrich** [comment]
Looks like I broke it when bringing double tap over to long-press

**Comment by RomRider** [comment]
I'll close this one in favor of #166

**Pull request closed without merging**
