### PR TITLE
 Haptic

### PR DESCRIPTION
**Pull request by RomRider**
**New Features**
* Support for haptic feedback for the [Beta IOS App](http://home-assistant.io/ios/beta) (Fixes #123)

### CODE REVIEW

**Comment by robbiet480** [comment]
All working in iOS app, thanks to @SeanPM5 for flagging me to this.

**Comment by iantrich** [comment]
Thanks for testing that @robbiet480

**Comment by iantrich** [comment]
Good to go after a rebase

**Comment by RomRider** [comment]
Thanks for testing @robbiet480!

**Pull request merged**
