### PR TITLE
Layout

### LINKED ISSUE #103: Help adding a space between name and state!
I just updated to `0.1.1` and noticed that the name and state now stack vertically vs horizontal on `0.0.8`

I was able to play around and get the alignment back to horizontal with a style tag
```
style:
  - display: flex
  - justify-content: center
```
but I cannot seem to get a space between the name and state no matter what I try.
here is a screenshot of my old frontend on `0.0.8`
frontend_old

and now the new on `0.1.1`
frontend

I'm getting closer to what I want but defiantly need some help getting the space back! 
Edit** - My lovelace is over here - https://github.com/Norien/Home-Assistant-Config/blob/master/ui-lovelace.yaml

### PR DESCRIPTION
**Pull request by RomRider**
**New features**
* `show_units`: true/false
* `units`: overrides the default units of a sensor
* overflowing text will be cut at the end with `...`
  image
* `layout`:
  Fixes #103 
  This option enables you to modify the layout of the card.
  
  It is fully compatible with every `show_*` option. Make sure you set `show_state: true` if you want to show the state

  Multiple values are possible, see the image below for examples:
  * `vertical` (default value if nothing is provided): Everything is centered vertically on top of each other
  * `icon_name_state`: Everything is aligned horizontally, name and state are concatenated
  * `name_state`: Icon sits on top of name and state concatenated on one line
  * `icon_name`: Icon and name are horizontally aligned, state is centered below
  * `icon_state`: Icon and state are horizontally aligned, name is centered below
  * `icon_name_state2nd`: Icon, name and state are horizontally aligned, name is above state
  * `icon_state_name2nd`: Icon, name and state are horizontally aligned, state is above name
  layout

### CODE REVIEW

**Comment by RomRider** [comment]
To be merged only after #106, will rebase once it's done if needed.

**Comment by Norien** [comment]
This is amazing! I can already think of a few cases where I'd like to have a tiny `icon - state` as well as my usual `name: state` 

I can't wait for this!

**Comment by B3voholic** [comment]
They all look great!  Appreciate your work!

**Comment by SeanPM5** [comment]
That looks fantastic, I've always wanted to be able to do that top horizontal layout style for certain buttons.

**Comment by RomRider** [comment]
If usefull, this is the test lovelace config:
```yaml
# Demo Layout
- cards:
  - type: vertical-stack
    cards:
    - type: "custom:button-card"
      color_type: label-card
      style:
        - font-weight: bold
        - text-transform: uppercase
      name: Layout
    - type: vertical-stack
      cards:
        - type: "custom:button-card"
          color_type: label-card
          name: icon_name_state
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          layout: icon_name_state

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          color_type: label-card
          name: name_state
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
        - type: "custom:button-card"
          color_type: label-card
          name: vertical (default)
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          layout: name_state
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          color_type: label-card
          name: icon_name
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
        - type: "custom:button-card"
          color_type: label-card
          name: icon_state
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          layout: icon_name
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          layout: icon_state

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          color_type: label-card
          name: icon_name with hidden state
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
        - type: "custom:button-card"
          color_type: label-card
          name: icon_state with hidden name
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: false
          layout: icon_name
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          show_name: false
          layout: icon_state

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          color_type: label-card
          name: icon_name_state2nd
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
        - type: "custom:button-card"
          color_type: label-card
          name: icon_state_name2nd
          color: var(--paper-item-icon-color)
          style:
            - font-weight: bold
            - padding: 5px 0px
    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          layout: icon_name_state2nd
        - type: "custom:button-card"
          entity: sensor.sensor1
          show_state: true
          layout: icon_state_name2nd
```

**Comment by RomRider** [comment]
I've tested every possible combination, so it should be good to be released.
Going to do that later.
Thanks

**Pull request merged**
